name: Android CI

on:
  push:
    branches: [ main, develop ] # Runs on pushes to main and develop
  pull_request:
    branches: [ main, develop ] # Runs on PRs targeting main and develop

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Set up Gradle with caching
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: wrapper
          # Only write cache on main & develop
          cache-read-only: ${{ github.ref != 'refs/heads/main' && github.ref != 'refs/heads/develop' }}

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew build --stacktrace

      - name: Upload APKs
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: apk-builds
          path: app/build/outputs/apk/**/*.apk

  lint:
    name: Android Lint
    runs-on: ubuntu-latest
    needs: build # Only run if build passes

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Set up Gradle with caching
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: wrapper
          cache-read-only: true # Don’t save cache in lint job

      - name: Run Android Lint
        run: ./gradlew lintDebug --stacktrace

      - name: Upload Lint Reports
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: lint-reports
          path: app/build/reports/lint-results-*.html

  test:
    name: Unit Tests
    runs-on: ubuntu-latest
    needs: build # Only run if build passes

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Set up Gradle with caching
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: wrapper
          cache-read-only: true # Don’t save cache in test job

      - name: Run Unit Tests
        run: ./gradlew testDebugUnitTest --stacktrace

      - name: Upload Test Reports
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-reports
          path: app/build/reports/tests/testDebugUnitTest
